language: go

go:
  - 1.7
  - tip
install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls      
  - go get github.com/philipf/minimax
script:
  - $HOME/gopath/bin/goveralls -service=travis-ci